DATASETS: !include configs/tin200/modules/dataset.yaml

MODEL:
  META_ARCHITECTURE:
    NAME: ClassificationModelBase
  PIXEL_MEAN: !include configs/tin200/modules/pixel_mean.yaml
  PIXEL_STD:  !include configs/tin200/modules/pixel_std.yaml
  BACKBONE:   !include configs/tin200/modules/backbone.yaml
  CLASSIFIER: !include configs/tin200/modules/classifier.yaml

SOLVER: !include configs/tin200/modules/swa.yaml

DATALOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

CUDNN_BENCHMARK: True
CUDNN_DETERMINISTIC: False

LOG_FREQUENCY: 4
NUM_DEVICES: -1
