DATASETS: !include configs/tin200/modules/dataset.yaml

MODEL:
  META_ARCHITECTURE:
    NAME: ClassificationModelBase
  PIXEL_MEAN: [0.4802, 0.4481, 0.3976, 0.4802, 0.4481, 0.3976]
  PIXEL_STD:  [0.2770, 0.2691, 0.2822, 0.2770, 0.2691, 0.2822]
  BACKBONE:
    NAME: build_resnet_backbone
    RESNET:
      CHANNELS: 6
      IN_PLANES: 64
      FIRST_BLOCK:
        USE_NORM_LAYER: True
        USE_ACTIVATION: True
        USE_POOL_LAYER: False
        CONV_KSP: [3, 1, 1]
        POOL_KSP: [3, 2, 1]
      BLOCK: BasicBlock
      SHORTCUT: ProjectionShortcut
      NUM_BLOCKS: [3, 4, 6, 3]
      WIDEN_FACTOR: 1
      CONV_LAYERS: Conv2d
      CONV_LAYERS_BIAS: False
      CONV_LAYERS_SAME_PADDING: False
      NORM_LAYERS: FilterResponseNorm2d
      ACTIVATIONS: SiLU
  CLASSIFIER:
    NAME: build_softmax_classifier
    SOFTMAX_CLASSIFIER:
      FEATURE_DIM: 512
      NUM_CLASSES: 200
      NUM_HEADS: 2
      USE_BIAS: True
      LINEAR_LAYERS: Linear
  MIMO:
    ENSEMBLE_SIZE: 2
    BATCH_REPEAT: 4
    SAMPLE_RHO: 0.5

# SOLVER: !include configs/tin200/modules/sgd.yaml
SOLVER:
  NUM_EPOCHS: 200
  BATCH_SIZE: 256
  VALID_FREQUENCY: 1
  VALID_FINALE: 20
  OPTIMIZER:
    NAME: SGD
    SGD:
      BASE_LR: 0.1
      WEIGHT_DECAY: 0.0001
      MOMENTUM: 0.9
      NESTEROV: True
  SCHEDULER:
    NAME: WarmupSimpleCosineLR
    WARMUP_SIMPLE_COSINE_LR:
      WARMUP_EPOCHS: 5
      WARMUP_METHOD: linear
      WARMUP_FACTOR: 0.01

DATALOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

CUDNN_BENCHMARK: True
CUDNN_DETERMINISTIC: False

LOG_FREQUENCY: 4
NUM_DEVICES: -1
