NAME: build_resnet_backbone
RESNET:
  CHANNELS: 3
  IN_PLANES: 16
  FIRST_BLOCK:
    USE_NORM_LAYER: True
    USE_ACTIVATION: True
    USE_POOL_LAYER: False
    CONV_KSP: [3, 1, 1]
    POOL_KSP: [3, 2, 1]
  BLOCK: BasicBlock
  SHORTCUT: ProjectionShortcut
  NUM_BLOCKS: [5, 5, 5]
  WIDEN_FACTOR: 2
  CONV_LAYERS: Conv2d_Bezier
  CONV_LAYERS_BIAS: True
  CONV_LAYERS_SAME_PADDING: True
  NORM_LAYERS: BatchNorm2d_Bezier
  ACTIVATIONS: SiLU
