# DEs
Single:
  - [outs-bn/cifar100/base-bn/0]
  - [outs-bn/cifar100/base-bn/1]
  - [outs-bn/cifar100/base-bn/2]
  - [outs-bn/cifar100/base-bn/3]
DE 2:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4]
DE 3:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5]
DE 4:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/1]
DE 5:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/1]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2]
DE 6:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6, outs-bn/cifar100/base-bn/1]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2]
DE 7:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6, outs-bn/cifar100/base-bn/7]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6, outs-bn/cifar100/base-bn/7, outs-bn/cifar100/base-bn/1]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/5, outs-bn/cifar100/base-bn/6, outs-bn/cifar100/base-bn/7, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2]

# Single + Beziers
Single + Bezier 1:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-1/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-2/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-3/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-4/0]
Single + Bezier 2:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-5/0]
Single + Bezier 3:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-5/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-5/0, outs-bn/cifar100/bezier-bn/0-1/0]
Single + Bezier 4:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-5/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-5/0, outs-bn/cifar100/bezier-bn/0-1/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-5/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0]

# DE + Beziers
DE 2 + Bezier:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/bezier-bn/0-1/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/bezier-bn/0-2/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/bezier-bn/0-3/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/bezier-bn/0-4/0]
DE 3 + Bezier:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/1-2/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/2-3/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/3-4/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/1-4/0]
DE 4 + Bezier:
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/1-2/0, outs-bn/cifar100/bezier-bn/1-3/0, outs-bn/cifar100/bezier-bn/2-3/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/2-3/0, outs-bn/cifar100/bezier-bn/2-4/0, outs-bn/cifar100/bezier-bn/3-4/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/3, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/bezier-bn/0-3/0, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/3-4/0, outs-bn/cifar100/bezier-bn/1-3/0, outs-bn/cifar100/bezier-bn/1-4/0]
  - [outs-bn/cifar100/base-bn/0, outs-bn/cifar100/base-bn/4, outs-bn/cifar100/base-bn/1, outs-bn/cifar100/base-bn/2, outs-bn/cifar100/bezier-bn/0-4/0, outs-bn/cifar100/bezier-bn/0-1/0, outs-bn/cifar100/bezier-bn/0-2/0, outs-bn/cifar100/bezier-bn/1-4/0, outs-bn/cifar100/bezier-bn/2-4/0, outs-bn/cifar100/bezier-bn/1-2/0]
