DATASETS: !include configs/cifar100/modules/dataset.yaml

MODEL:
  META_ARCHITECTURE:
    NAME: ClassificationModelBase
  PIXEL_MEAN: !include configs/cifar100/modules/pixel_mean.yaml
  PIXEL_STD:  !include configs/cifar100/modules/pixel_std.yaml
  BACKBONE:   !include configs/cifar100/modules/backbone_bezier_bn.yaml
  CLASSIFIER: !include configs/cifar100/modules/classifier_bezier.yaml

SOLVER: !include configs/cifar100/modules/sgd.yaml

DATALOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

CUDNN_BENCHMARK: True
CUDNN_DETERMINISTIC: False

LOG_FREQUENCY: 4
NUM_DEVICES: -1
