DATASETS: !include configs/cifar100/modules/dataset.yaml

MODEL:
  META_ARCHITECTURE:
    NAME: ClassificationModelBase
  PIXEL_MEAN: [0.5072, 0.4866, 0.4410, 0.5072, 0.4866, 0.4410, 0.5072, 0.4866, 0.4410]
  PIXEL_STD:  [0.2673, 0.2564, 0.2760, 0.2673, 0.2564, 0.2760, 0.2673, 0.2564, 0.2760]
  BACKBONE:
    NAME: build_resnet_backbone
    RESNET:
      CHANNELS: 9
      IN_PLANES: 16
      FIRST_BLOCK:
        USE_NORM_LAYER: True
        USE_ACTIVATION: True
        USE_POOL_LAYER: False
        CONV_KSP: [3, 1, 1]
        POOL_KSP: [3, 2, 1]
      BLOCK: BasicBlock
      SHORTCUT: ProjectionShortcut
      NUM_BLOCKS: [5, 5, 5]
      WIDEN_FACTOR: 5
      CONV_LAYERS: Conv2d
      CONV_LAYERS_BIAS: True
      CONV_LAYERS_SAME_PADDING: True
      NORM_LAYERS: FilterResponseNorm2d
      ACTIVATIONS: SiLU
  CLASSIFIER:
    NAME: build_softmax_classifier
    SOFTMAX_CLASSIFIER:
      FEATURE_DIM: 320
      NUM_CLASSES: 100
      NUM_HEADS: 2
      USE_BIAS: True
      LINEAR_LAYERS: Linear
  MIMO:
    ENSEMBLE_SIZE: 2
    BATCH_REPEAT: 4
    SAMPLE_RHO: 0.

SOLVER:
  NUM_EPOCHS: 200
  BATCH_SIZE: 512
  VALID_FREQUENCY: 1
  VALID_FINALE: 20
  OPTIMIZER:
    NAME: SGD
    SGD:
      BASE_LR: 0.1
      WEIGHT_DECAY: 0.0003
      MOMENTUM: 0.9
      NESTEROV: False
  SCHEDULER:
    NAME: WarmupSimpleCosineLR
    WARMUP_SIMPLE_COSINE_LR:
      WARMUP_EPOCHS: 5
      WARMUP_METHOD: linear
      WARMUP_FACTOR: 0.01

DATALOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True

CUDNN_BENCHMARK: True
CUDNN_DETERMINISTIC: False

LOG_FREQUENCY: 4
NUM_DEVICES: -1
