# DEs
Single:
  - [outs-swa/tin200/base-swa/0]
  - [outs-swa/tin200/base-swa/1]
  - [outs-swa/tin200/base-swa/2]
  - [outs-swa/tin200/base-swa/3]
DE 2:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4]
DE 3:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5]
DE 4:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/1]
DE 5:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/1]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2]
DE 6:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6, outs-swa/tin200/base-swa/1]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2]
DE 7:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6, outs-swa/tin200/base-swa/7]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6, outs-swa/tin200/base-swa/7, outs-swa/tin200/base-swa/1]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/5, outs-swa/tin200/base-swa/6, outs-swa/tin200/base-swa/7, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2]

# Single + Beziers
Single + Bezier 1:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-1/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-2/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-3/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-4/0]
Single + Bezier 2:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-5/0]
Single + Bezier 3:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-5/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-5/0, outs-swa/tin200/bezier-swa/0-1/0]
Single + Bezier 4:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-5/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-5/0, outs-swa/tin200/bezier-swa/0-1/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-5/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0]

# Single + Beziers
# Single + Bezier-Align 1:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-1/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-2/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-3/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-4/0]
# Single + Bezier-Align 2:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-5/0]
# Single + Bezier-Align 3:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-5/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-5/0, outs-swa/tin200/bezier-swa-align/0-1/0]
# Single + Bezier-Align 4:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-5/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-5/0, outs-swa/tin200/bezier-swa-align/0-1/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-5/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0]

# DE + Beziers
DE 2 + Bezier:
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/bezier-swa/0-1/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/bezier-swa/0-2/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/bezier-swa/0-3/0]
  - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/bezier-swa/0-4/0]
# DE 3 + Bezier:
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/1-2/0]
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/2-3/0]
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/3-4/0]
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/1, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/1-4/0]
# DE 4 + Bezier:
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/1-2/0, outs-swa/tin200/bezier-swa/1-3/0, outs-swa/tin200/bezier-swa/2-3/0]
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/2, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/2-3/0, outs-swa/tin200/bezier-swa/2-4/0, outs-swa/tin200/bezier-swa/3-4/0]
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/3, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/1, outs-swa/tin200/bezier-swa/0-3/0, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/3-4/0, outs-swa/tin200/bezier-swa/1-3/0, outs-swa/tin200/bezier-swa/1-4/0]
#   - [outs-swa/tin200/base-swa/0, outs-swa/tin200/base-swa/4, outs-swa/tin200/base-swa/1, outs-swa/tin200/base-swa/2, outs-swa/tin200/bezier-swa/0-4/0, outs-swa/tin200/bezier-swa/0-1/0, outs-swa/tin200/bezier-swa/0-2/0, outs-swa/tin200/bezier-swa/1-4/0, outs-swa/tin200/bezier-swa/2-4/0, outs-swa/tin200/bezier-swa/1-2/0]

# DE + Beziers
# DE 2 + Bezier-Align:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/1, outs-swa/tin200/bezier-swa-align/0-1/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/2, outs-swa/tin200/bezier-swa-align/0-2/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/3, outs-swa/tin200/bezier-swa-align/0-3/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/4, outs-swa/tin200/bezier-swa-align/0-4/0]
# DE 3 + Bezier-Align:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/1, outs-swa/tin200/base-align/2, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/1-2/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/2, outs-swa/tin200/base-align/3, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/2-3/0]
# #   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/3, outs-swa/tin200/base-align/4, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/3-4/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/4, outs-swa/tin200/base-align/1, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/1-4/0]
# DE 4 + Bezier-Align:
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/1, outs-swa/tin200/base-align/2, outs-swa/tin200/base-align/3, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/1-2/0, outs-swa/tin200/bezier-swa-align/1-3/0, outs-swa/tin200/bezier-swa-align/2-3/0]
# #   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/2, outs-swa/tin200/base-align/3, outs-swa/tin200/base-align/4, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/2-3/0, outs-swa/tin200/bezier-swa-align/2-4/0, outs-swa/tin200/bezier-swa-align/3-4/0]
# #   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/3, outs-swa/tin200/base-align/4, outs-swa/tin200/base-align/1, outs-swa/tin200/bezier-swa-align/0-3/0, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/3-4/0, outs-swa/tin200/bezier-swa-align/1-3/0, outs-swa/tin200/bezier-swa-align/1-4/0]
#   - [outs-swa/tin200/base-align/0, outs-swa/tin200/base-align/4, outs-swa/tin200/base-align/1, outs-swa/tin200/base-align/2, outs-swa/tin200/bezier-swa-align/0-4/0, outs-swa/tin200/bezier-swa-align/0-1/0, outs-swa/tin200/bezier-swa-align/0-2/0, outs-swa/tin200/bezier-swa-align/1-4/0, outs-swa/tin200/bezier-swa-align/2-4/0, outs-swa/tin200/bezier-swa-align/1-2/0]
