# DEs
Single:
  - [tin200/base/0]
  - [tin200/base/1]
  - [tin200/base/2]
  - [tin200/base/3]
DE 2:
  - [tin200/base/0, tin200/base/1]
  - [tin200/base/0, tin200/base/2]
  - [tin200/base/0, tin200/base/3]
  - [tin200/base/0, tin200/base/4]
DE 3:
  - [tin200/base/0, tin200/base/1, tin200/base/2]
  - [tin200/base/0, tin200/base/2, tin200/base/3]
  - [tin200/base/0, tin200/base/3, tin200/base/4]
  - [tin200/base/0, tin200/base/4, tin200/base/5]
DE 4:
  - [tin200/base/0, tin200/base/1, tin200/base/2, tin200/base/3]
  - [tin200/base/0, tin200/base/2, tin200/base/3, tin200/base/4]
  - [tin200/base/0, tin200/base/3, tin200/base/4, tin200/base/5]
  - [tin200/base/0, tin200/base/4, tin200/base/5, tin200/base/1]
DE 5:
  - [tin200/base/0, tin200/base/1, tin200/base/2, tin200/base/3, tin200/base/4]
  - [tin200/base/0, tin200/base/2, tin200/base/3, tin200/base/4, tin200/base/5]
  - [tin200/base/0, tin200/base/3, tin200/base/4, tin200/base/5, tin200/base/1]
  - [tin200/base/0, tin200/base/4, tin200/base/5, tin200/base/1, tin200/base/2]
DE 6:
  - [tin200/base/0, tin200/base/1, tin200/base/2, tin200/base/3, tin200/base/4, tin200/base/5]
  - [tin200/base/0, tin200/base/2, tin200/base/3, tin200/base/4, tin200/base/5, tin200/base/6]
  - [tin200/base/0, tin200/base/3, tin200/base/4, tin200/base/5, tin200/base/6, tin200/base/1]
  - [tin200/base/0, tin200/base/4, tin200/base/5, tin200/base/6, tin200/base/1, tin200/base/2]
DE 7:
  - [tin200/base/0, tin200/base/1, tin200/base/2, tin200/base/3, tin200/base/4, tin200/base/5, tin200/base/6]
  - [tin200/base/0, tin200/base/2, tin200/base/3, tin200/base/4, tin200/base/5, tin200/base/6, tin200/base/7]
  - [tin200/base/0, tin200/base/3, tin200/base/4, tin200/base/5, tin200/base/6, tin200/base/7, tin200/base/1]
  - [tin200/base/0, tin200/base/4, tin200/base/5, tin200/base/6, tin200/base/7, tin200/base/1, tin200/base/2]

# Single + Beziers
Single + Bezier 1:
  - [tin200/base/0, tin200/bezier/0-1/0]
  - [tin200/base/0, tin200/bezier/0-2/0]
  - [tin200/base/0, tin200/bezier/0-3/0]
  - [tin200/base/0, tin200/bezier/0-4/0]
Single + Bezier 2:
  - [tin200/base/0, tin200/bezier/0-1/0, tin200/bezier/0-2/0]
  - [tin200/base/0, tin200/bezier/0-2/0, tin200/bezier/0-3/0]
  - [tin200/base/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0]
  - [tin200/base/0, tin200/bezier/0-4/0, tin200/bezier/0-5/0]
Single + Bezier 3:
  - [tin200/base/0, tin200/bezier/0-1/0, tin200/bezier/0-2/0, tin200/bezier/0-3/0]
  - [tin200/base/0, tin200/bezier/0-2/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0]
  - [tin200/base/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0, tin200/bezier/0-5/0]
  - [tin200/base/0, tin200/bezier/0-4/0, tin200/bezier/0-5/0, tin200/bezier/0-1/0]
Single + Bezier 4:
  - [tin200/base/0, tin200/bezier/0-1/0, tin200/bezier/0-2/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0]
  - [tin200/base/0, tin200/bezier/0-2/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0, tin200/bezier/0-5/0]
  - [tin200/base/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0, tin200/bezier/0-5/0, tin200/bezier/0-1/0]
  - [tin200/base/0, tin200/bezier/0-4/0, tin200/bezier/0-5/0, tin200/bezier/0-1/0, tin200/bezier/0-2/0]

# # Single + Beziers
Single + Bezier-Align 1:
  - [tin200/base-align/0, tin200/bezier-align/0-1/0]
  - [tin200/base-align/0, tin200/bezier-align/0-2/0]
  - [tin200/base-align/0, tin200/bezier-align/0-3/0]
  - [tin200/base-align/0, tin200/bezier-align/0-4/0]
Single + Bezier-Align 2:
  - [tin200/base-align/0, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0]
  - [tin200/base-align/0, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0]
  - [tin200/base-align/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0]
  - [tin200/base-align/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-5/0]
Single + Bezier-Align 3:
  - [tin200/base-align/0, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0]
  - [tin200/base-align/0, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0]
  - [tin200/base-align/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-5/0]
  - [tin200/base-align/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-5/0, tin200/bezier-align/0-1/0]
Single + Bezier-Align 4:
  - [tin200/base-align/0, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0]
  - [tin200/base-align/0, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-5/0]
  - [tin200/base-align/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-5/0, tin200/bezier-align/0-1/0]
  - [tin200/base-align/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-5/0, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0]

# DE + Beziers
DE 2 + Bezier:
  - [tin200/base/0, tin200/base/1, tin200/bezier/0-1/0]
  - [tin200/base/0, tin200/base/2, tin200/bezier/0-2/0]
  - [tin200/base/0, tin200/base/3, tin200/bezier/0-3/0]
  - [tin200/base/0, tin200/base/4, tin200/bezier/0-4/0]
DE 3 + Bezier:
  - [tin200/base/0, tin200/base/1, tin200/base/2, tin200/bezier/0-1/0, tin200/bezier/0-2/0, tin200/bezier/1-2/0]
  - [tin200/base/0, tin200/base/2, tin200/base/3, tin200/bezier/0-2/0, tin200/bezier/0-3/0, tin200/bezier/2-3/0]
  - [tin200/base/0, tin200/base/3, tin200/base/4, tin200/bezier/0-3/0, tin200/bezier/0-4/0, tin200/bezier/3-4/0]
  - [tin200/base/0, tin200/base/4, tin200/base/1, tin200/bezier/0-4/0, tin200/bezier/0-1/0, tin200/bezier/1-4/0]
DE 4 + Bezier:
  - [tin200/base/0, tin200/base/1, tin200/base/2, tin200/base/3, tin200/bezier/0-1/0, tin200/bezier/0-2/0, tin200/bezier/0-3/0, tin200/bezier/1-2/0, tin200/bezier/1-3/0, tin200/bezier/2-3/0]
  - [tin200/base/0, tin200/base/2, tin200/base/3, tin200/base/4, tin200/bezier/0-2/0, tin200/bezier/0-3/0, tin200/bezier/0-4/0, tin200/bezier/2-3/0, tin200/bezier/2-4/0, tin200/bezier/3-4/0]
  - [tin200/base/0, tin200/base/3, tin200/base/4, tin200/base/1, tin200/bezier/0-3/0, tin200/bezier/0-4/0, tin200/bezier/0-1/0, tin200/bezier/3-4/0, tin200/bezier/1-3/0, tin200/bezier/1-4/0]
  - [tin200/base/0, tin200/base/4, tin200/base/1, tin200/base/2, tin200/bezier/0-4/0, tin200/bezier/0-1/0, tin200/bezier/0-2/0, tin200/bezier/1-4/0, tin200/bezier/2-4/0, tin200/bezier/1-2/0]

# # DE + Beziers
DE 2 + Bezier-Align:
  - [tin200/base-align/0, tin200/base-align/1, tin200/bezier-align/0-1/0]
  - [tin200/base-align/0, tin200/base-align/2, tin200/bezier-align/0-2/0]
  - [tin200/base-align/0, tin200/base-align/3, tin200/bezier-align/0-3/0]
  - [tin200/base-align/0, tin200/base-align/4, tin200/bezier-align/0-4/0]
DE 3 + Bezier-Align:
  - [tin200/base-align/0, tin200/base-align/1, tin200/base-align/2, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0, tin200/bezier-align/1-2/0]
  - [tin200/base-align/0, tin200/base-align/2, tin200/base-align/3, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0, tin200/bezier-align/2-3/0]
#   - [tin200/base-align/0, tin200/base-align/3, tin200/base-align/4, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0, tin200/bezier-align/3-4/0]
  - [tin200/base-align/0, tin200/base-align/4, tin200/base-align/1, tin200/bezier-align/0-4/0, tin200/bezier-align/0-1/0, tin200/bezier-align/1-4/0]
DE 4 + Bezier-Align:
  - [tin200/base-align/0, tin200/base-align/1, tin200/base-align/2, tin200/base-align/3, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0, tin200/bezier-align/1-2/0, tin200/bezier-align/1-3/0, tin200/bezier-align/2-3/0]
#   - [tin200/base-align/0, tin200/base-align/2, tin200/base-align/3, tin200/base-align/4, tin200/bezier-align/0-2/0, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0, tin200/bezier-align/2-3/0, tin200/bezier-align/2-4/0, tin200/bezier-align/3-4/0]
#   - [tin200/base-align/0, tin200/base-align/3, tin200/base-align/4, tin200/base-align/1, tin200/bezier-align/0-3/0, tin200/bezier-align/0-4/0, tin200/bezier-align/0-1/0, tin200/bezier-align/3-4/0, tin200/bezier-align/1-3/0, tin200/bezier-align/1-4/0]
  - [tin200/base-align/0, tin200/base-align/4, tin200/base-align/1, tin200/base-align/2, tin200/bezier-align/0-4/0, tin200/bezier-align/0-1/0, tin200/bezier-align/0-2/0, tin200/bezier-align/1-4/0, tin200/bezier-align/2-4/0, tin200/bezier-align/1-2/0]
