KD - DE 2:
  - [outs-kd/tin200/base-kd/de2/0]
  - [outs-kd/tin200/base-kd/de2/1]
  - [outs-kd/tin200/base-kd/de2/2]
  - [outs-kd/tin200/base-kd/de2/3]

KD - DE 3:
  - [outs-kd/tin200/base-kd/de3/0]
  - [outs-kd/tin200/base-kd/de3/1]
  - [outs-kd/tin200/base-kd/de3/2]
  - [outs-kd/tin200/base-kd/de3/3]

KD - DE 4:
  - [outs-kd/tin200/base-kd/de4/0]
  - [outs-kd/tin200/base-kd/de4/1]
  - [outs-kd/tin200/base-kd/de4/2]
  - [outs-kd/tin200/base-kd/de4/3]
