BE 2:
  - [outs-be/tin200/batch-ens/2/0:0, outs-be/tin200/batch-ens/2/0:1]
  - [outs-be/tin200/batch-ens/2/1:0, outs-be/tin200/batch-ens/2/1:1]
  - [outs-be/tin200/batch-ens/2/2:0, outs-be/tin200/batch-ens/2/2:1]
  - [outs-be/tin200/batch-ens/2/3:0, outs-be/tin200/batch-ens/2/3:1]

BE 3:
  - [outs-be/tin200/batch-ens/3/0:0, outs-be/tin200/batch-ens/3/0:1, outs-be/tin200/batch-ens/3/0:2]
  - [outs-be/tin200/batch-ens/3/1:0, outs-be/tin200/batch-ens/3/1:1, outs-be/tin200/batch-ens/3/1:2]
  - [outs-be/tin200/batch-ens/3/2:0, outs-be/tin200/batch-ens/3/2:1, outs-be/tin200/batch-ens/3/2:2]
  - [outs-be/tin200/batch-ens/3/3:0, outs-be/tin200/batch-ens/3/3:1, outs-be/tin200/batch-ens/3/3:2]

BE 4:
  - [outs-be/tin200/batch-ens/4/0:0, outs-be/tin200/batch-ens/4/0:1, outs-be/tin200/batch-ens/4/0:2, outs-be/tin200/batch-ens/4/0:3]
  - [outs-be/tin200/batch-ens/4/1:0, outs-be/tin200/batch-ens/4/1:1, outs-be/tin200/batch-ens/4/1:2, outs-be/tin200/batch-ens/4/1:3]
  - [outs-be/tin200/batch-ens/4/2:0, outs-be/tin200/batch-ens/4/2:1, outs-be/tin200/batch-ens/4/2:2, outs-be/tin200/batch-ens/4/2:3]
  - [outs-be/tin200/batch-ens/4/3:0, outs-be/tin200/batch-ens/4/3:1, outs-be/tin200/batch-ens/4/3:2, outs-be/tin200/batch-ens/4/3:3]
