DATASETS: !include configs/in1k/modules/dataset.yaml
BEZIER_MODEL:
  META_ARCHITECTURE:
    NAME: ClassificationModelBase
  PIXEL_MEAN: !include configs/in1k/modules/pixel_mean.yaml
  PIXEL_STD:  !include configs/in1k/modules/pixel_std.yaml
  BACKBONE:   !include configs/in1k/modules/backbone_bezier.yaml
  CLASSIFIER: !include configs/in1k/modules/classifier_bezier.yaml
  CHECKPOINT: TO_BE_SET

MODEL:
  META_ARCHITECTURE:
    NAME: BridgeModelBase
  BASE_IN_PLANES: 2048
  REQUIRES:
    - layer12
    - layer13
  BACKBONES: [14, 15, 16]
  TYPE: 1
  SLIM_FACTOR: 1

SOLVER:
  NUM_EPOCHS: 50
  BATCH_SIZE: 512
  VALID_FREQUENCY: 5
  VALID_FINALE: 10
  OPTIMIZER:
    NAME: SGD
    SGD:
      BASE_LR: 0.1
      WEIGHT_DECAY: 0.00001
      MOMENTUM: 0.9
      NESTEROV: False
  SCHEDULER:
    NAME: WarmupSimpleCosineLR
    WARMUP_SIMPLE_COSINE_LR:
      WARMUP_EPOCHS: 5
      WARMUP_METHOD: linear
      WARMUP_FACTOR: 0.01
  MATCH: log_confidences
  MIXUP_ALPHA: 0.0
  REGULARIZATION: 0.

DATALOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True

CUDNN_BENCHMARK: True
CUDNN_DETERMINISTIC: False

LOG_FREQUENCY: 5
NUM_DEVICES: -1
