NUM_EPOCHS: 100
BATCH_SIZE: 256
VALID_FREQUENCY: 5
VALID_FINALE: 20
OPTIMIZER:
  NAME: SGD
  SGD:
    BASE_LR: 0.1
    WEIGHT_DECAY: 0.00001
    MOMENTUM: 0.9
    NESTEROV: False
SCHEDULER:
  NAME: WarmupSimpleCosineLR
  WARMUP_SIMPLE_COSINE_LR:
    WARMUP_EPOCHS: 5
    WARMUP_METHOD: linear
    WARMUP_FACTOR: 0.01
