NUM_EPOCHS: 200
BATCH_SIZE: 128
VALID_FREQUENCY: 1
VALID_FINALE: 20
OPTIMIZER:
  NAME: SGD
  SGD:
    SUFFIX_BE:
      - alpha_be
      - gamma_be
    BASE_LR: 0.1
    BASE_LR_BE: 0.05
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BE: 0.0000
    MOMENTUM: 0.9
    MOMENTUM_BE: 0.9
    NESTEROV: True
    NESTEROV_BE: True
SCHEDULER:
  NAME: WarmupSimpleCosineLR
  WARMUP_SIMPLE_COSINE_LR:
    WARMUP_EPOCHS: 5
    WARMUP_METHOD: linear
    WARMUP_FACTOR: 0.01
