NUM_EPOCHS: 200
BATCH_SIZE: 128
VALID_FREQUENCY: 1
VALID_FINALE: 20
OPTIMIZER:
  NAME: SGD
  SGD:
    BASE_LR: 0.1
    WEIGHT_DECAY: 0.0005
    MOMENTUM: 0.9
    NESTEROV: True
SCHEDULER:
  NAME: WarmupSimpleCosineLR
  WARMUP_SIMPLE_COSINE_LR:
    WARMUP_EPOCHS: 5
    WARMUP_METHOD: linear
    WARMUP_FACTOR: 0.01
SWA_START_EPOCH: 150
